/* tslint:disable */
//ts-nocheck

//imported methods
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');


//pass env variables from the .env into process.env
require('dotenv').config();
const environment = argv.environment;


//helper function to copy environment variables into respective files, or create file if it doens't exist
function writeFileUsingFs(targetPath, environmentFileContent) {
    writeFile(targetPath, environmentFileContent, function (err) {
        if (err) {
            console.log(err);
        }

        if (environmentFileContent !== '') {
            console.log(`wrote variables to ${targetPath}`);
        }
    })
}


//providing path to the environments directory
const envDirectory = './src/environments';

// creates environments directory if it doesn't exist
if (!existsSync(envDirectory)) {
    mkdirSync(envDirectory);
}


//creates environment files if they don't exist
writeFileUsingFs('./src/environments/environment.prod.ts', '');
writeFileUsingFs('./src/environments/environment.ts', '');

//generate environment variables that contain API keys
//checks enviroment
const isProduction = environment === 'prod';

//choose targetPath
const targetPath = isProduction
    ? './src/environments/environment.prod.ts'
    : './src/environments/environment.ts';

const environmentFileContent = `
    // this file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

    export const environment = {
    production: ${isProduction},
    FLICKR_API_KEY: '${process.env.FLICKR_API_KEY}'
    };
`;

//append data to the target
writeFileUsingFs(targetPath, environmentFileContent);

/* tslint:enable */